CursoMVC/CapaPresentacionTienda/Controllers/TiendaController.cs
using CapaEntidad;
using CapaNegocio;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using CapaEntidad.Paypal;
using CapaPresentacionTienda.Filter;
namespace CapaPresentacionTienda.Controllers
{
    public class TiendaController : Controller
    {
        // GET: Tienda
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DetalleProducto(int idproducto = 0)
        {

            Producto oProducto = new Producto();
            bool conversion;


            oProducto = new CN_Producto().Listar().Where(p => p.IdProducto == idproducto).FirstOrDefault();


            if (oProducto != null)
            {
                oProducto.Base64 = CN_Recursos.ConvertirBase64(Path.Combine(oProducto.RutaImagen, oProducto.NombreImagen), out conversion);
                oProducto.Extension = Path.GetExtension(oProducto.NombreImagen);
            }

            return View(oProducto);
        }


        [HttpGet]
        public JsonResult ListaCategorias()
        {
            List<Categoria> lista = new List<Categoria>();
            lista = new CN_Categoria().Listar();
            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ListarMarcaporCategoria(int idcategoria)
        {
            List<Marca> lista = new List<Marca>();
            lista = new CN_Marca().ListarMarcaporCategoria(idcategoria);
            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult ListarProducto(int idcategoria, int idmarca, int nroPagina)
        {
            List<Producto> lista = new List<Producto>();

            bool conversion;

            //lista = new CN_Producto().Listar().Select(p => new Producto()
            //{
            //    IdProducto = p.IdProducto,
            //    Nombre = p.Nombre,
            //    Descripcion = p.Descripcion,
            //    oMarca = p.oMarca,
            //    oCategoria = p.oCategoria,
            //    Precio = p.Precio,
            //    Stock = p.Stock,
            //    RutaImagen = p.RutaImagen,
            //    Base64 = CN_Recursos.ConvertirBase64(Path.Combine(p.RutaImagen,p.NombreImagen), out conversion),
            //    Extension = Path.GetExtension(p.NombreImagen),
            //    Activo = p.Activo
            //}).Where(p =>
            //    p.oCategoria.IdCategoria == (idcategoria == 0 ? p.oCategoria.IdCategoria : idcategoria) &&
            //    p.oMarca.IdMarca == (idmarca == 0 ? p.oMarca.IdMarca : idmarca) &&
            //    p.Stock > 0 && p.Activo == true
            // ).ToList();
            int _TotalRegistros;
            int _TotalPaginas;

            lista = new CN_Producto().ObtenerProductos(idmarca, idcategoria, nroPagina, 8, out _TotalRegistros, out _TotalPaginas).Select(p => new Producto()
            {
                IdProducto = p.IdProducto,
                Nombre = p.Nombre,
                Descripcion = p.Descripcion,
                oMarca = p.oMarca,
                oCategoria = p.oCategoria,
                Precio = p.Precio,
                Stock = p.Stock,
                RutaImagen = p.RutaImagen,
                Base64 = CN_Recursos.ConvertirBase64(Path.Combine(p.RutaImagen, p.NombreImagen), out conversion),
                Extension = Path.GetExtension(p.NombreImagen),
                Activo = p.Activo
            }).ToList();

            var jsonresult = Json(new { data = lista, totalRegistros = _TotalRegistros, totalPaginas = _TotalPaginas }, JsonRequestBehavior.AllowGet);
            jsonresult.MaxJsonLength = int.MaxValue;

            return jsonresult;
        }

        [HttpPost]
        public JsonResult AgregarCarrito(int idproducto)
        {

            int idcliente = ((Cliente)Session["Cliente"]).IdCliente;

            bool existe = new CN_Carrito().ExisteCarrito(idcliente, idproducto);

            bool respuesta = false;

            string mensaje = string.Empty;

            if (existe)
            {
                mensaje = "El producto ya existe en el carrito";

            }
            else
            {

                respuesta = new CN_Carrito().OperacionCarrito(idcliente, idproducto, true, out mensaje);
            }

            return Json(new { respuesta = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);


        }

        [HttpGet]
        public JsonResult CantidadEnCarrito()
        {

            int idcliente = ((Cliente)Session["Cliente"]).IdCliente;
            int cantidad = new CN_Carrito().CantidadEnCarrito(idcliente);
            return Json(new { cantidad = cantidad }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ListarProductosCarrito()
        {

            int idcliente = ((Cliente)Session["Cliente"]).IdCliente;

            List<Carrito> oLista = new List<Carrito>();

            bool conversion;

            oLista = new CN_Carrito().ListarProducto(idcliente).Select(oc => new Carrito()
            {
                oProducto = new Producto()
                {
                    IdProducto = oc.oProducto.IdProducto,
                    Nombre = oc.oProducto.Nombre,
                    oMarca = oc.oProducto.oMarca,
                    Precio = oc.oProducto.Precio,
                    RutaImagen = oc.oProducto.RutaImagen,
                    Base64 = CN_Recursos.ConvertirBase64(Path.Combine(oc.oProducto.RutaImagen, oc.oProducto.NombreImagen), out conversion),
                    Extension = Path.GetExtension(oc.oProducto.NombreImagen)

                },
                Cantidad = oc.Cantidad
            }).ToList();

            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public JsonResult OperacionCarrito(int idproducto, bool sumar)
        {

            int idcliente = ((Cliente)Session["Cliente"]).IdCliente;


            bool respuesta = false;

            string mensaje = string.Empty;


            respuesta = new CN_Carrito().OperacionCarrito(idcliente, idproducto, true, out mensaje);


            return Json(new { respuesta = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);


        }

        [HttpPost]
        public JsonResult EliminarCarrito(int idproducto)
        {

            int idcliente = ((Cliente)Session["Cliente"]).IdCliente;

            bool respuesta = false;

            string mensaje = string.Empty;

            respuesta = new CN_Carrito().EliminarCarrito(idcliente, idproducto);

            return Json(new { respuesta = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ObtenerDepartamento()
        {

            List<Departamento> oLista = new List<Departamento>();

            oLista = new CN_Ubicacion().ObtenerDepartamento();

            return Json(new { lista = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ObtenerProvincia(string IdDepartamento)
        {

            List<Provincia> oLista = new List<Provincia>();

            oLista = new CN_Ubicacion().ObtenerProvincia(IdDepartamento);

            return Json(new { lista = oLista }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult ObtenerDistrito(string IdDepartamento, string IdProvincia)
        {

            List<Distrito> oLista = new List<Distrito>();

            oLista = new CN_Ubicacion().ObtenerDistrito(IdDepartamento, IdProvincia);

            return Json(new { lista = oLista }, JsonRequestBehavior.AllowGet);
        }

        [ValidarSession]
        [Authorize]
        public ActionResult Carrito()
        {
            return View();
        }
        [HttpPost]
        public async Task<JsonResult> ProcesarPago(List<Carrito> oListaCarrito, Venta oVenta)
        {

            decimal total = 0;
            DataTable detalle_venta = new DataTable();
            detalle_venta.Locale = new CultureInfo("es-PE");
            detalle_venta.Columns.Add("IdProducto", typeof(string));
            detalle_venta.Columns.Add("Cantidad", typeof(int));
            detalle_venta.Columns.Add("Total", typeof(decimal));


            List<Item> oListaItem = new List<Item>();

            foreach (Carrito oCarrito in oListaCarrito)
            {
                decimal subtotal = Convert.ToDecimal(oCarrito.Cantidad.ToString()) * oCarrito.oProducto.Precio;

                total += subtotal;

                oListaItem.Add(new Item()
                {
                    name = oCarrito.oProducto.Nombre,
                    quantity = oCarrito.Cantidad.ToString(),
                    unit_amount = new UnitAmount()
                    {
                        currency_code = "MXN",
                        value = oCarrito.oProducto.Precio.ToString("G", new CultureInfo("es-PE"))
                    }


                });

                detalle_venta.Rows.Add(new object[] {
                    oCarrito.oProducto.IdProducto,
                    oCarrito.Cantidad,
                    subtotal
                });
            }


            PurchaseUnit purchaseUnit = new PurchaseUnit()
            {
                amount = new Amount()
                {
                    currency_code = "MXN",
                    value = total.ToString("G", new CultureInfo("es-PE")),
                    breakdown = new Breakdown()
                    {
                        item_total = new ItemTotal()
                        {
                            currency_code = "MXN",
                            value = total.ToString("G", new CultureInfo("es-PE")),
                        }
                    }

                },

CursoMVC/CapaPresentacionTienda/Views/Tienda/DetalleProducto.cshtml
@model CapaEntidad.Producto
@{
    ViewBag.Title = "DetalleProducto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            @*<div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="data:image/@Html.DisplayTextFor(m => m.Extension);base64,@Html.DisplayTextFor(m=> m.Base64)" alt="..." /></div>*@
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="@Html.DisplayTextFor(m => m.RutaImagen)" alt="..." /></div>
            <div class="col-md-6">
                <div class="small mb-1">Marca: @Html.DisplayTextFor(m => m.oMarca.Descripcion)</div>
                <h1 class="display-5 fw-bolder">@Html.DisplayTextFor(m => m.Nombre)</h1>
                <div class="fs-5 mb-5">
                    @*<span class="text-decoration-line-through">$45.00</span>*@
                    <span>@Html.DisplayTextFor(m => m.Precio) USD</span>
                </div>
                <p class="lead">@Html.DisplayTextFor(m => m.Descripcion)</p>
                <div class="d-flex">

                    <a href="@Url.Action("Index","Tienda")" class="btn btn-danger w-50 text-center me-3">
                        <i class="fas fa-undo-alt"></i> Volver

                    </a>

                    @if (Session["Cliente"] != null)
                    {

                        <button class="btn btn-success agregarcarrito flex-shink-0 w-50" type="button" data-idproducto="@Html.DisplayTextFor(m => m.IdProducto)">
                            <i class="fas fa-cart-plus"></i> Agregar al carrito
                        </button>
                    }



                </div>
            </div>
        </div>
    </div>
</section>


@section scripts{


    <script>

         $(document).on("click", "button.agregarcarrito", function () {

            console.log($(this).data("idproducto"))

            jQuery.ajax({
                url: '@Url.Action("AgregarCarrito", "Tienda")',
                type: "POST",
                data: JSON.stringify({ idproducto: $(this).data("idproducto") }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    if (data.respuesta) {

                        MostrarCantidadCarrito();

                        @*swal({
                            title: "Agregado al carrito",
                            text: "¿Desea ir al carrito?",
                            type: "success",
                            showCancelButton: true,
                            confirmButtonClass: "btn-primary",
                            confirmButtonText: "Si",
                            cancelButtonText: "No",
                            closeOnConfirm: true
                        }, function () {

                            window.location.href = '@Url.Action("Carrito","Tienda")'

                        })*@
                        swal("", "Agregado al carrito", "success");

                    } else {
                        swal("", data.mensaje, "warning");
                    }
                }

            });

        })

    </script>

}

CursoMVC/CapaPresentacionTienda/Views/Tienda/MisCompras.cshtml
@model List<CapaEntidad.DetalleVenta>
@{
    ViewBag.Title = "MisCompras";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">

    <div class="row mt-5">
        <div class="col-sm-12">

            @{
                if (Model.Count > 0)
                {

                    foreach (var item in Model)
                    {

                        <div class="row mb-3">
                            <div class="col-sm-12">

                                <div class="card">
                                    <div class="card-body bg-light">
                                        <h6>ID TRANSACCION : @item.IdTransaccion</h6>
                                        <div class="table-responsive">

                                            <table class="table table-bordered">

                                                <thead>
                                                    <tr>
                                                        <th>Imagen</th>
                                                        <th>Producto</th>
                                                        <th>Precio Unitario</th>
                                                        <th>Cantidad</th>
                                                        <th>Sub Total</th>
                                                    </tr>

                                                </thead>
                                                <tbody class="bg-white">
                                                    <tr>
                                                        <td>
                                                            <img class="card-img-top mb-5 mb-md-0" src="@item.oProducto.RutaImagen" style="width:120px;height:120px" />
                                                        </td>
                                                        <td valign="middle">
                                                            @item.oProducto.Nombre
                                                        </td>
                                                        <td valign="middle">
                                                            $ @item.oProducto.Precio MXN
                                                        </td>
                                                        <td valign="middle">
                                                            @item.Cantidad
                                                        </td>
                                                        <td valign="middle">
                                                            $ @item.Total MXN
                                                        </td>
                                                    </tr>

                                                </tbody>


                                            </table>
                                        </div>

                                    </div>


                                </div>

                            </div>
                        </div>

                    }


                }
                else
                {
                    <div class="row mb-3">
                        <div class="col-sm-12 text-center">
                            <h1>No se encontraron compras</h1>
                        </div>
                    </div>


                }


            }

        </div>


    </div>

</div> 

CursoMVC/CapaPresentacionTienda/Views/Tienda/PagoEfectuado.cshtml
@{
    ViewBag.Title = "PagoEfectuado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">


    <div class="col-sm-12 text-center">
        <br /><br />

        @{
            if ((bool)ViewData["Status"])
            {

                <h1 class="text-success">Gracias!</h1>
                <i class="far fa-check-circle fa-9x text-success"></i>

                <h2 class="text-success"> Su pago fue realizado con exito</h2>
                <h4> ID de Transacción : @ViewData["IdTransaccion"]</h4>

                <br />
                <a href="@Url.Action("Index", "Tienda")" class="btn btn-primary">Volver a la tienda</a>
            }
            else
            {


                <h1 class="text-danger">Lo sentimos</h1>

                <i class="fas fa-exclamation-circle fa-9x text-danger"></i>


                <h2 class="text-danger"> Su pago no fue realizado</h2>

                <br />
                <a href="@Url.Action("Index", "Tienda")" class="btn btn-primary">Volver a la tienda</a>
            }



        }


    </div>
</div>